/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Módulo predefinido
 * OpenAPI spec version: 1.0.0
 */

export type AuthLogout200 = {
  error: boolean;
  message: string;
  data: null;
};
