/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Módulo predefinido
 * OpenAPI spec version: 1.0.0
 */
import type { AuthLogin200Data } from "./authLogin200Data";

export type AuthLogin200 = {
  error: boolean;
  message: string;
  data: AuthLogin200Data;
};
