/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Módulo predefinido
 * OpenAPI spec version: 1.0.0
 */

export type AuthLoginBody = {
  /**
   * @minLength 3
   * @maxLength 255
   */
  password: string;
  /** @maxLength 255 */
  email: string;
};
