/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Módulo predefinido
 * OpenAPI spec version: 1.0.0
 */
import type { UserResource } from "./userResource";

export type AuthRegister201Data = {
  user: UserResource;
  token: string;
};
