/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Módulo predefinido
 * OpenAPI spec version: 1.0.0
 */
import type { AuthRegister201Data } from "./authRegister201Data";

export type AuthRegister201 = {
  error: boolean;
  message: string;
  data: AuthRegister201Data;
};
