/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Módulo predefinido
 * OpenAPI spec version: 1.0.0
 */

export type AuthRegisterBody = {
  /**
   * @minLength 3
   * @maxLength 255
   */
  name: string;
  /** @maxLength 255 */
  email: string;
  /**
   * @minLength 8
   * @maxLength 255
   * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$
   */
  password: string;
  role_id: string;
};
