/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Módulo predefinido
 * OpenAPI spec version: 1.0.0
 */

export interface UserResource {
  id: string;
  name: string;
  email: string;
  roles: string[];
  created_at: string;
}
